# Generated by Django 2.1.5 on 2019-02-09 00:17
import json
from django.db import migrations
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'data.json'


def load_data(apps, schema_editor):
    Theatre = apps.get_model('shops', 'Theatre')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for theatre in objects['elements']:
            type = theatre.get('type', None)
            try:
                if type == 'node':
                    tags = theatre['tags']
                    name = tags.get('name', 'no-name')
                    longitude = theatre.get('lon', 0)
                    latitude = theatre.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Theatre(name=name, location=location).save()
            except KeyError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_theatre'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]

